### ISSUE TITLE
[Bug] "config" command does not add new keys to qmk.ini file

### ISSUE THREAD

**Issue by rynoV** [qmk/qmk_cli#121]
### Describe the Bug

When my `~/.config/qmk/qmk.ini` file does not have a key already in it, `qmk config` doesn't add that key. For example if `user.keyboard` isn't in the `qmk.ini` file, running `qmk config user.keyboard=keyboard` doesn't make any changes to `qmk.ini`. However if I add `user.keyboard` manually, then `qmk config` will update that key correctly.

I tried `qmk --log-file qmk.log --log-file-level debug config user.keyboard=keyboard` and that didn't produce a log file.

### Additional Context?

```
qmk --version
1.0.0
```

I installed for the first time today using `python3 -m pip install --user qmk` (following [the setup instructions here](https://docs.qmk.fm/#/newbs_getting_started)).

```
python3 --version
Python 3.9.7
```

OS: Pop!_OS 21.10 x86_64

Let me know if you need any more information, and thanks for your help!

**Comment by LovesTha** [comment]
Using qmk 1.1.2 on nixos I have very similar behaviour. But once I added a user.keyboard setting then I could set my layout and that worked.

**Comment by LovesTha** [comment]
But having a valid keyboard and layout set still doesn't make `qmk flash` find them, I still have to specify them

**Comment by fauxpark** [comment]
This might be a https://github.com/clueboard/milc issue.
