### ISSUE TITLE
[Bug] qmk compile -kb/-km violates POSIX tradition

### ISSUE THREAD

**Issue by avalanchemarramrat** [qmk/qmk_cli#152]
### Describe the Bug

> Multi-digit options should not be allowed.

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

The -kb and -km options violate POSIX. They should be changed to a single character, such as -b or -m.

**Comment by tzarc** [comment]
We're not intending to change this.
