### ISSUE TITLE
[Feature Request] Please properly document how to setup the CLI

### ISSUE THREAD

**Issue by itaranto** [qmk/qmk_cli#166]
### Description

Right now,  the [documentation](https://docs.qmk.fm/#/cli_configuration) doesn't say anything about setting up the CLI.

I had to figure out by myself that `qmk setup` is needed for correctly using the application.

Also, the documentation talks about `qmk complie` and `qmk flash` all over the place without mentioning that `qmk setup` is needed for even those sub-commands to appear!

**Comment by keyboard-magpie** [comment]
There is a whole page devoted to this here: https://docs.qmk.fm/#/newbs_getting_started
