### ISSUE TITLE
[Bug] Doesn't clone qmk/qmk_firmware with proxy while http.proxy and http.proxy are set

### ISSUE THREAD

**Issue by ChihHao-Su** [qmk/qmk_cli#179]
### Describe the Bug

I need to visit Github with a proxy, I have set `http.proxy` and `https.proxy`. But It seems that qmk cli is not using my proxy, so it just hangs after I answer “y” to “Would you like to clone qmk/qmk_firmware to /home/...../qmk_firmware? [y/n]”.
```sh
➜  ~ qmk setup
☒ Could not find qmk_firmware!
Would you like to clone qmk/qmk_firmware to /home/chihhao-su/qmk_firmware? [y/n] y
正複製到 '/home/chihhao-su/qmk_firmware'...

```

### Additional Context?

Version: qmk-1.1.5-py2.py3-none-any.whl

**Comment by nooges** [comment]
QMK cli is just calling `git` to do the clone, so you will need to configure git to use your proxy like this: https://gist.github.com/evantoli/f8c23a37eb3558ab8765

**Comment by ChihHao-Su** [comment]
> QMK cli is just calling git to do the clone, so you will need to configure git to use your proxy like this: https://gist.github.com/evantoli/f8c23a37eb3558ab8765

Thank you, I have set git configurations.

-----------------

Okay, I figured out what's happing. When QMK cli is cloning `qmk/qmk_firmware`, there's no output like “remote: .....” “Receiving objects: .....”, and that makes me think it's stuck. In fact it's cloning fine.
