### ISSUE TITLE
[Bug] When installing via pip, receive error "SetuptoolsDeprecationWarning: Invalid dash-separated options"

### ISSUE THREAD

**Issue by ipurton** [qmk/qmk_cli#191]
### Describe the Bug

After running installation command for the QMK CLI, I receive the following error message. Full log is provided in context and system info is provided below.

System:
Kernel: 5.15.0-126-generic x86_64 bits: 64 compiler: gcc v: 11.4.0
    Desktop: Cinnamon 6.0.4 tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0
    Distro: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy

Python 3.10.12, pip 24.3.1

```
/home/ruby/.local/lib/python3.10/site-packages/setuptools/dist.py:452: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
```

### Additional Context?

[20241212_QMK_CLI_pipinstallerror.txt](https://github.com/user-attachments/files/18119305/20241212_QMK_CLI_pipinstallerror.txt)

**Comment by fauxpark** [comment]
Not a QMK issue.
https://github.com/manrajgrover/halo/blob/master/setup.cfg
