### ISSUE TITLE
[Bug] Not compatible with milc < 1.9

### ISSUE THREAD

**Issue by liljaylj** [qmk/qmk_cli#192]
### Describe the Bug

in the official Arch Linux repository there is an outdated version of the python-milc package (1.8.0). this makes the qmk script unusable, because in milc versions before 1.9.0 there was no `set_options` attribute.

to restore the script's functionality, I suggest adding an attribute check. if it is not there, then fallback to now-deprecated `set_metadata`.

**Comment by tzarc** [comment]
QMK CLI is marked to require 1.9.0 or later: https://github.com/qmk/qmk_cli/blob/master/setup.cfg#L40

I'm not sure catering for out-of-date downstream packages is the approach we'd like to take.

I'd suggest that the fix would be to get the Arch `python-milc` package bumped -- we don't control that sadly.

**Comment by liljaylj** [comment]
ok. it is understandable.

reported to arch linux repo gitlab (https://gitlab.archlinux.org/archlinux/packaging/packages/python-milc/-/issues/1).

for now, as a workaround, installed qmk in virtual environment until python-milc package will be updated.

**Comment by liljaylj** [comment]
closing as not planned
