### ISSUE TITLE
[Feature Request] Enhance qmk setup to add upstream

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_cli#21]
When users run `qmk setup <username>/qmk_firmware` we should add `qmk/qmk_firmware` as an remote named upstream.

**Comment by skullydazed** [comment]
Worth considering: should we always add upstream, even when both origin and upstream will point to the same location? This would make it easier for users to switch to their own fork later.

**Comment by nooges** [comment]
My take is yes, so we don’t have to worry if someone is referring to our repo as origin or upstream, and we can just issue guidance based on knowing it’s upstream.
