### ISSUE TITLE
Do not hardcode 'bin/qmk' in qmk_cli/subcommands/setup.py

### ISSUE THREAD

**Issue by kromka-chleba** [qmk/qmk_cli#25]
Hello, can you not hardcode 'bin/qmk' in the qmk_cli/subcommands/setup.py file?
I'm trying to package your software in Guix (http://guix.gnu.org/) and this hardcoded path makes my life harder - it breaks the "qmk setup" command:
```
Ψ QMK Doctor is checking your environment.
Ψ Detected Linux.
☒ Can't run `bin/qmk --version`
```

Using "/usr/bin/env qmk" will solve the issue.

Thanks.

**Comment by skullydazed** [comment]
For the time being that check is required, `bin/qmk` is not the same as the global qmk cli. If you can't run `bin/qmk` some of the make infrastructure may break. Currently that codepath is only used by JSON keymaps, but we have plans to use it for other things in the future.

**Comment by kromka-chleba** [comment]
> For the time being that check is required, `bin/qmk` is not the same as the global qmk cli. If you can't run `bin/qmk` some of the make infrastructure may break.

So I need `bin/qmk` for the tests? I got some errors, likely because of this, and skipped the tests.
Anyway, can you make qmk_cli detect where the `qmk` binary was installed and use it instead of the hardcoded `bin/qmk`?
By hardcoding it, you make it harder for distributions like Guix or Nix to package it.
I can fix it in my package by patching your source code, but solution like this is a dirty hack.

**Comment by kromka-chleba** [comment]
The thing is Guix stores packages in /gnu/store instead of the standard directories. On Nix this is /nix/store.

**Comment by skullydazed** [comment]
> Anyway, can you make qmk_cli detect where the qmk binary was installed and use it instead of the hardcoded bin/qmk?

No, the test in question would not be useful if we did that. We need the script `bin/qmk` inside qmk_firmware to be executable. If that script can not be executed it's an error condition that needs to be fixed.

> By hardcoding it, you make it harder for distributions like Guix or Nix to package it.

The script in question is part of the qmk_firmware build infrastructure. It's an unfortunate accident of history that it shares a name with the qmk that is part of `qmk_cli`, but that was a necessary tradeoff to get where we are today.

**Comment by kromka-chleba** [comment]
>The script in question is part of the qmk_firmware build infrastructure. It's an unfortunate accident of history that it shares a name with the qmk script that is part of qmk_cli, but that was a necessary tradeoff to get where we are today.

Okay, thanks. With this info I managed to fix my Guix package.
