### ISSUE TITLE
[Bug] 0.0.41 breaks setup on MSYS

### ISSUE THREAD

**Issue by zvecr** [qmk/qmk_cli#47]
## Describe the Bug

![image](https://user-images.githubusercontent.com/16520359/112736886-07710300-8f4e-11eb-98aa-107421895e8d.png)

## Additional Context

fe42ab3534e7156156c75c8e05dd49ce2e69ef1e introduces a slightly different behaviour for running doctor as part of setup.

 https://github.com/qmk/qmk_cli/blob/8f5b8e83c0a7e847db132230a561840600f60801/qmk_cli/subcommands/setup.py#L93

Where argv[0] contains a path that now gets munged by python.

In my brief testing, 
* calling cygpath on these variable before cli.run makes no difference
* MSYS2_ARG_CONV_EXCL does not change this pathing behaviour

**Comment by zvecr** [comment]
Changing the line to ` doctor_command = [sys.argv[0], 'doctor'] ` seems to work fine

**Comment by skullydazed** [comment]
Version 0.0.44 should fix this.
