### ISSUE TITLE
[Bug] No module named 'hid'

### ISSUE THREAD

**Issue by danniel3** [qmk/qmk_cli#55]
## Describe the Bug

After running qmk setup the first time, everything installed, and I got an error message. Now no qmk commands work.

Message:

Error: %s: %s ('ModuleNotFoundError', ModuleNotFoundError("No module named 'hid'"))
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qmk_cli/script_qmk.py", line 74, in main
    import qmk.cli  # noqa
  File "/home/danniel/qmk_firmware/lib/python/qmk/cli/__init__.py", line 158, in <module>
    from . import console  # noqa
  File "/home/danniel/qmk_firmware/lib/python/qmk/cli/console.py", line 9, in <module>
    import hid
ModuleNotFoundError: No module named 'hid'

## Additional Context

Running Arch, installed via sudo pacman -S qmk, with all the dependencies.

**Comment by danniel3** [comment]
Solved it by installing pip, then installing hid, flake8, nose2, and yapf, which were apparently also missing. 

I wonder if this can be put into the qmk setup command, so that it automatically pulls these missing packages for the next person.

**Comment by humb1t** [comment]
Same thing
