### ISSUE TITLE
[Bug] No standard setup.py; what's the new way to package qmk_cli?

### ISSUE THREAD

**Issue by 0mp** [qmk/qmk_cli#92]
### Describe the Bug

I'm the maintainer of the qmk package for FreeBSD. The main benefit of having a package for the qmk cli is that users can just install the qmk package and get all the dependencies easily at once.

The packaging process of the qmk cli used to be quite easy when the setup.py was present. I'm not sure what's the current recommended way of doing it. Could you document what's the best way to build, stage and install the qmk cli now?

Thanks!

**Comment by skullydazed** [comment]
The new way is to use the build module.

Prerequisite:
    `python3 -m pip install build`

Build command:
    `python3 -m build`

For reference the documentation I used while putting this together is here: https://packaging.python.org/guides/distributing-packages-using-setuptools/

**Comment by 0mp** [comment]
Thank you for the links.

Out of curiosity, is there a reason why the project switched to this method rather than keeping setup.py around?

**Comment by skullydazed** [comment]
It's the currently recommended method, compliant with PEP-517. As our metadata is all static it's recommended to only use setup.cfg.

**Comment by 0mp** [comment]
I see. Thanks a lot for explaining the transition. Cheers!
